[package]
name = "mos6502-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bitflags = "2.4.0"
serde = { version = "1.0.183", features = [ "derive" ] }
thiserror = "1.0.44"
typetag = "0.2.13"
